### PR TITLE
Widget updates

### LINKED ISSUE #71: Update htmlwidgets to use latest releases
Compare each current renderer to latest release: 

- [x] aeExplorer.js 3.4.1 - current
- [x] safetyDeltaDelta.js 1.0.0 - current
- [x] aeTimelines.js 2.1.6 - current            
- [x] safetyHistogram.js 2.5.0 - current
- [x] hepExplorer.js 1.3.1 -> 1.4.2              
- [x] safetyOutlierExplorer.js 2.7.0 - current
- [x] nepExplorer.js 0.9.0 - current
- [x] safetyResultsOverTime.js 2.3.3 - current
- [x] paneledOutlierExplorer.js 1.1.4 - current
- [x] safetyShiftPlot.js 2.1.3 - current

### LINKED ISSUE #88: AESER is an undocumented requirement for safetyTimeline widget
AESER is required for safetyTimeline, but isn't included in the current default metadata.

### PR DESCRIPTION
**Pull request by jwildfire**
# Overview

- Adds init function for aeTimelines giving support for custom Severity and Seriousness mappings.  Fix #71. 
- Updates hep-explorer widget from v1.3.1 to version 1.4.2. All release notes are [here](https://github.com/SafetyGraphics/hep-explorer/releases), but the main additions are the nRatio should be available as an option on the x-axis and pAlt should be calculated for all participants by default (see arrows in screenshot below). Fix #88. 
- 
image

This should wrap up the updates for v0.3! Once this is merged I'll work on getting this to CRAN and then try to finalize safetyGraphics v2.1.

# Test Notes

- For hep-explorer, confirm functionality listed above is present and no other obvious bugs are found. 
- Test code for aeTimeline: 
```
#Confirm that new metadata mappings for severity and seriousness work as expected in aetimelines

customSevSer <- safetyData::adam_adae %>%
rename(sev=AESEV) %>%
rename(ser=AESER) 

safetyGraphicsApp(
    domainData = list(aes=customSevSer),
    mapping=list(aes=list(severity_col="sev", serious_col="ser"))
)

# Extra color added when new category added. Not 100% ideal, but ok. 
customSevSer <- safetyData::adam_adae %>%
rename(sev=AESEV) %>%
rename(ser=AESER) %>%
mutate(sev = if_else(sev=="MILD","WILD!",sev))


safetyGraphicsApp(
    domainData = list(aes=customSevSer),
    mapping=list(aes=list(severity_col="sev", serious_col="ser"))
)
```

### CODE REVIEW

**Review by xni7 — COMMENTED** [review]
Looks great @jwildfire !  a couple of minor comments

- [x] **hepExplorer**
     - suggest adding reference to R and nR ratio somewhere (ideally in the widget), e.g. 
        + https://www.gastrojournal.org/article/S0016-5085(14)01484-X/fulltext
        +  or [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6986960/#:~:text=The%20nR%20is%20calculated%20as%20(the%20highest%20AST%20or%20ALT/ULN)/(ALP/ULN)%3B%20AST%20is%20substituted%20for%20ALT%2C%20if%20the%20AST%20yields%20a%20greater%20R%2Dratio.)
    - `baseline`  and `analysis`  mapping in `hepExplorer()`  do  not match hepexplorer.js parameterization
https://github.com/SafetyGraphics/safetyCharts/blob/4652165469b7481ca5a1c6ac42c81a5b3cfa0c76/R/hepExplorer.R#L53-L56
expecting baseline as a list
https://github.com/SafetyGraphics/safetyCharts/blob/4652165469b7481ca5a1c6ac42c81a5b3cfa0c76/inst/htmlwidgets/lib/hep-explorer-1.4.2/hepexplorer.js#L255-L258
mDish is working with the following code.

   ``` # enable mDish plot example
    mapping_baseline <- list(
        measure_col = "PARAM",
        measure_values = list(
            ALT = "Alanine Aminotransferase (U/L)",
            AST = "Aspartate Aminotransferase (U/L)",
            TB = "Bilirubin (umol/L)",
            ALP = "Alkaline Phosphatase (U/L)"
        ),
        ## mDish does not work with this mapping
        # baseline_flag_col = "ABLFL",
        # baseline_flag_values = "Y",
        ## mDish works with a baseline list, 
        baseline = list(
            value_col = "ABLFL",
            values = "Y"
        ),
        analysis_flag_col = "",
        analysis_flag_values = "",
        id_col = "USUBJID",
        value_col = "AVAL",
        normal_col_low = "A1LO",
        normal_col_high = "A1HI",
        studyday_col = "ADY",
        visit_col = "VISIT",
        visitn_col = "VISITNUM",
        unit_col = ""
    )
    ```

- [x] **aeTimelines**. Looks great! Only comment is the `ASTDY` has huge negative values in `safetyData::adam_adae`. Perhaps can  filter out in vignette for better viewing experience. 

    ```r
    # Extra color added when new category added. Not 100% ideal, but ok.
    customSevSer <- safetyData::adam_adae %>%
        filter(ASTDY > -50) %>% # add a filter to make the timeline more viewable
        rename(sev = AESEV) %>%
        rename(ser = AESER) %>%
        mutate(sev = if_else(sev == "MILD", "WILD!", sev))
    
    
    safetyGraphicsApp(
        domainData = list(aes = customSevSer),
        mapping = list(aes = list(severity_col = "sev", serious_col = "ser"))
    )
    ```

**Comment by jwildfire** [comment]
> suggest adding reference to R and nR ratio somewhere (ideally in the widget), e.g.
> * https://www.gastrojournal.org/article/S0016-5085(14)01484-X/fulltext
> * or [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6986960/#:~:text=The%20nR%20is%20calculated%20as%20(the%20highest%20AST%20or%20ALT/ULN)/(ALP/ULN)%3B%20AST%20is%20substituted%20for%20ALT%2C%20if%20the%20AST%20yields%20a%20greater%20R%2Dratio.)

Good idea - filed https://github.com/SafetyGraphics/hep-explorer/issues/335

**Comment by jwildfire** [comment]
> * `baseline`  and `analysis`  mapping in `hepExplorer()`  do  not match hepexplorer.js parameterization

I updated the docs a bit in #104 on Friday and cleaned this up.

FWIW, the default mapping was pasted from the safetyGraphicsApp() export which includes `baseline_flag_X` and `analysis_flag_X`. As you noted, they're not currently used in hepExplorer though. Should probably write a little `hepexplorer_init` to set them up in the safetyGraphics app. That actually obfuscates the new the hepExplorer function a bit though, so maybe we should just delete those non-standard mappings. Not sure ... Will file an issue and leave it for a future release.

**Comment by jwildfire** [comment]
Actually going to just delete those options. See #105.

**Comment by jwildfire** [comment]
> * Only comment is the `ASTDY` has huge negative values in `safetyData::adam_adae`. Perhaps can  filter out in vignette for better viewing experience.

Yeah, I've been meaning to do this in the hosted example. Added a comment [here](https://github.com/SafetyGraphics/safetyGraphics/issues/649)

**Pull request merged**
