### PR TITLE
paneledOutlierExplorer()

### PR DESCRIPTION
**Pull request by MayaGans**
I'm SO close but I can't seem to figure out this error....

I see you have an `init` function so my mental model was that I'd be able to do this:

```
adbds <- read.csv("https://raw.githubusercontent.com/RhoInc/data-library/master/data/clinical-trials/renderer-specific/adbds.csv")

init_paneledOutlierExplorer(adbds, ...) %>%
  paneledOutlierExplorer()
```

As a first step I'm supplying the default settings as arguments to the init function using the settings from https://github.com/RhoInc/paneled-outlier-explorer/blob/master/src/defaultSettings.js, 

But I'm getting the error 

```
The value "VISIT" for the this.config.x.column setting does not match any column in the provided dataset.
```

I'll keep poking around but figured I'd alert you since I'm so close and you'll probably beat me to figuring this out... 

Thanks!!

Oh I'm happy to make checks in the function too once I understand what the user NEEDS to supply as arguments (like returning an error if the column name in your config doesnt exist?)

### CODE REVIEW

**Comment by jwildfire** [comment]
Oooh, nice! Thanks for putting this together. I'll dig in sometime this weekend and see if I can help debug.

**Comment by jwildfire** [comment]
@MayaGans I just did a quick refactor to set up a `paneledOutlierExplorer()` function that passes the settings object you built to `render_widget` (same logic as the new-ish `hepExplorer`). `render_widget` reuses the same logic that's used to export widgets in the safetyGraphics app, but supports adding arbitrary settings via `...` as shown in the examples. 

Take a look and let me know what you think. Happy to chat sometime next week if needed.

**Comment by jwildfire** [comment]
> I see you have an `init` function so my mental model was that I'd be able to do this:
> 
> ```
> adbds <- read.csv("https://raw.githubusercontent.com/RhoInc/data-library/master/data/clinical-trials/renderer-specific/adbds.csv")
> 
> init_paneledOutlierExplorer(adbds, ...) %>%
>   paneledOutlierExplorer()
> ```
> 
> As a first step I'm supplying the default settings as arguments to the init function using the settings from https://github.com/RhoInc/paneled-outlier-explorer/blob/master/src/defaultSettings.js,

Oh, btw, I've mostly used the `init` functions for implementing custom data flows in the `safetyGraphicsApp()`. No reason I can see your use case wouldn't work though ... I *think* your error was because the js renderer doesn't want `x.column` and `y.column` set by the user, but it's been a while since I've looked at the details, so I'm not 100% sure. 

At any rate, I just stripped down your config a bit, and it seems to be happy now.

**Comment by MayaGans** [comment]
ooooh I get it now! Thank you SO much this was super helpful (and I understand a lot more about how I'd create and use new charts in SG which is a huge added bonus too!!)

**Review by jwildfire — APPROVED** [review]

**Pull request merged**
