### PR TITLE
Updates for Tplyr

### PR DESCRIPTION
**Pull request by elimillera**
Per review of https://github.com/SafetyGraphics/safetyGraphics/pull/453

Really awesome to see that Tplyr is being used like this.

I through a couple of changes into the `tplyr_demog_chart` to show off a bit more a Tplyr.

- A total group was added to show all treatment groups in one.
- I also added a total row for both layers that just has the total counts.
- Did a little bit of post-processing to remove the ordering columns and mask the row labels

If there is anything you can think of that might improve Tplyr for safetyCharts/safetyGraphics we would really appreciate the feedback.

### CODE REVIEW

**Comment by jwildfire** [comment]
Looks good - table is nice and easy to follow now! Ran fine for me with default config. 

Here are a few nit-picky things that we can consider if we want to fine tune this and get it closer to a "production" table. 
- I wonder if this would be better rendered in something other than DT. Not sure the interactivity adds anything here. Maybe use Kable? Or just print? Or we could even try rendering an RTF ... not quite sure how that would work though. 
- At a minimum we should try to change the number of rows shown so that there isn't a page break. 
- Is it easy to generate human readable column headers? 
- Should we drop the row numbers? 
- Remove highlighting on final column (this is due to a [sloppy css issue over in safetyGraphics](https://github.com/SafetyGraphics/safetyGraphics/issues/467))

Also happy to merge this PR now, and tackle this stuff later. Just let me know your preference!

**Comment by elimillera** [comment]
@jwildfire Hey Jeremy. Thanks for the reminder. I've been a bit busy recently so I haven't been able to grab this yet. I've put it on my weekend todo list so I will have these updates by monday

**Comment by jwildfire** [comment]
No rush at all, @elimillera. Was actually just demoing some of GitHub PM functionality and used this PR as an example :)

**Comment by elimillera** [comment]
Hey @jwildfire, quick question. I'm working on this and I got a couple of the points figured out but I can't seem to find where the actual rendering is happening. Can you point me to where the Kable/DT calls are happening for the Tplyr Table?

**Comment by jwildfire** [comment]
@elimillera - The actual render occurs [here](mod_chartsRenderStatic.R) in `mod_chartsRenderStatic.R`. This [little test app](https://github.com/SafetyGraphics/safetyGraphics/blob/dev/tests/testthat/module_examples/chartsRenderStatic/app.R) is probably the best place to see it in action, and could easily be modified to test the new table in a slightly simplified context.

**Comment by jwildfire** [comment]
I should also add that I'm open to extending `if/then/else` to support additional renderers or modifying the framework to use a more robust functional approach.

**Comment by elimillera** [comment]
Hey @jwildfire,
I pushed another updates here that adds nice column headers. I also added a PR to safetyGraphics to remove the page break and row numbers. I've been researching how to add a different renderer, I think huxtable is a really good choice here, and I think we could go straight from that huxtable table to allow the user to download an RTF. I'm still looking into how the package works so it would be a couple of weeks before I could get that in.

**Comment by jwildfire** [comment]
@elimillera Just putting a note to let you know that I'm working on safetyCharts some the next few days, so if you need anything here, I'm happy to take a look!

**Comment by elimillera** [comment]
Hey @jwildfire, I'm moving this work into a branch in the SG repo instead of my personal one. I think I'm getting the hang of the workflow at this point so I should be able to be much faster

**Pull request closed without merging**
